name: hexo-build
on:
  push:
    branches:
      - main
env:
  TZ: Asia/Shanghai
jobs:
  www-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node.js v12.14.0
        uses: actions/setup-node@v2
        with:
          node-version: "12.14.0"
          cache: "npm"
          cache-dependency-path: www/package-lock.json
      - name: Install dependencies
        run: |
          cd www/
          npm install
      - name: Deploy
        run: |
          rm -f www/source/_posts
          cp -r _posts/ www/source/_posts/
          cd www/
          npm run build
          cd public/
          git config --global init.defaultBranch master
          git init
          git config user.name "${{secrets.GIT_NAME}}"
          git config user.email "${{secrets.GIT_EMAIL}}"
          git add .
          git commit -m "Site updated" -q
          git push -f -q "https://${{secrets.GH_TOKEN}}@${{secrets.GH_REF_BUTTERFLY}}" master
          git push -f -q "https://${{ secrets.CD_USER }}:${{secrets.CD_TOKEN}}@${{secrets.CD_REF_BUTTERFLY}}" master
  blog-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node.js v12.14.0
        uses: actions/setup-node@v2
        with:
          node-version: "12.14.0"
          cache: "npm"
          cache-dependency-path: blog/package-lock.json
      - name: Install dependencies
        run: |
          cd blog/
          npm install
      - name: Deploy
        run: |
          rm -f blog/source/_posts
          cp -r _posts/ blog/source/_posts/
          cd blog/
          npm run build
          cd public/
          git config --global init.defaultBranch master
          git init
          git config user.name "${{secrets.GIT_NAME}}"
          git config user.email "${{secrets.GIT_EMAIL}}"
          git add .
          git commit -m "Site updated" -q
          git push -f -q "https://${{secrets.GH_TOKEN}}@${{secrets.GH_REF_NEXT}}" master:master
          git push -f -q "https://${{ secrets.CD_USER }}:${{secrets.CD_TOKEN}}@${{secrets.CD_REF_NEXT}}" master:master
